services:
  web:
    build: ./web
    volumes:
      - ./web/:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser_password
      - POSTGRES_DB=db_dev

volumes:
  postgres_data:
